services:
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   ports:
  #     - '${BACKEND_PORT}:${BACKEND_PORT}'
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}
  #   depends_on:
  #     - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    environment:
      - NODE_ENV=development

  # db:
  #   image: postgres:latest
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
