FROM node:20 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm set strict-ssl false && npm install --only=production

COPY . .

RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

USER node

EXPOSE 3001

CMD ["node", "dist/app.js"]
